name: Tests

# Controls when the action will run.
on:
  pull_request:
  push:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: tests-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  docs:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Don't upgrade python version; there's a bug in 3.10 sphinx
          python-version: "3.9"
          cache: 'pip'
      - name: Build the documentation.
        run: nox -s docs
  mypy:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Check type annotations.
        run: nox -s mypy
  showcase:
    strategy:
      matrix:
        target: [showcase, showcase_alternative_templates]
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Run showcase tests.
        run: nox -s ${{ matrix.target }}
  showcase-mtls:
    if: ${{ false }}            # TODO(dovs): reenable when #1218 is fixed
    strategy:
      matrix:
        target: [showcase_mtls, showcase_mtls_alternative_templates]
      max-parallel: 1
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup temp directory
        run: |
          sudo mkdir -p /tmp/workspace/tests/cert/
          sudo chown -R ${USER} /tmp/workspace/
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Copy mtls files
        run: cp tests/cert/mtls.* /tmp/workspace/tests/cert/
      - name: Run showcase tests.
        run:  |

            ./gapic-showcase run --mtls-ca-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-cert=/tmp/workspace/tests/cert/mtls.crt --mtls-key=/tmp/workspace/tests/cert/mtls.key &

            cd ..
            nox -s ${{ matrix.target }}
  showcase-unit:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        variant: ['', _alternative_templates, _mixins, _alternative_templates_mixins]
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "${{ matrix.python }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          cache: 'pip'
      - name: Run unit tests.
        run: nox -s showcase_unit${{ matrix.variant }}-${{ matrix.python }}
  showcase-unit-add-iam-methods:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Run unit tests.
        run: nox -s showcase_unit_add_iam_methods
  showcase-mypy:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    strategy:
      matrix:
        variant: ['', _alternative_templates]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Typecheck the generated output.
        run: nox -s showcase_mypy${{ matrix.variant }}
  snippetgen:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Check autogenerated snippets.
        run: nox -s snippetgen
  unit:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Run unit tests.
        run: nox -s unit-${{ matrix.python }}
  fragment:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        variant: ['', _alternative_templates]
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Run fragment tests.
        run: nox -s fragment${{ matrix.variant }}-${{ matrix.python }}
  integration:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    container: gcr.io/gapic-images/googleapis
    steps:
      - uses: actions/checkout@v3
      - name: Cache Bazel files
        id: cache-bazel
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          # Note: if the container is updated, the key needs to be updated as well.
          key: ${{ runner.os }}-bazel-20210105-${{ secrets.CACHE_VERSION }}
      - name: Cache not found
        if: steps.cache-bazel.outputs.cache-hit != 'true'
        run: |
          echo "No cache found."
      - name: Cache found
        if: steps.cache-bazel.outputs.cache-hit == 'true'
        run: |
          echo -n "Cache found. Cache size: "
          du -sh ~/.cache/bazel
          echo "If the cache seems broken, update the CACHE_VERSION secret in"
          echo "https://github.com/googleapis/gapic-generator-python/settings/secrets/actions"
          echo "(use any random string, any GUID will work)"
          echo "and it will start over with a clean cache."
          echo "The old one will disappear after 7 days."
      - name: Integration Tests
        run: bazel test //tests/integration/...

  goldens-lint:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Run blacken and lint on the generated output.
        run: |
          nox -f tests/integration/goldens/asset/noxfile.py -s blacken lint_setup_py lint
          nox -f tests/integration/goldens/credentials/noxfile.py -s blacken lint_setup_py lint
          nox -f tests/integration/goldens/eventarc/noxfile.py -s blacken lint_setup_py lint
          nox -f tests/integration/goldens/logging/noxfile.py -s blacken lint_setup_py lint
          nox -f tests/integration/goldens/redis/noxfile.py -s blacken lint_setup_py lint
  style-check:
    runs-on: gcr.io/cloud-devrel-public-resources/gapic-generator-python-ci:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Check diff
        run: |
            find gapic tests -name "*.py" -not -path 'tests/**/goldens/*' | xargs autopep8 --diff --exit-code
